### PR TITLE
Unit tests

### PR DESCRIPTION
**Pull request by nvarner**
I wrote a bunch of unit tests to make sure that what we write doesn't fall apart under unusual stresses. The tests are automatically run on Travis CI (you should be able to see the results of the tests on this PR).

### CODE REVIEW

**Review by itsmerachel — APPROVED** [review]
yes a+ you're bill gates now

**Comment by nvarner** [comment]
Yay great

**Comment by itsmerachel** [comment]
there are no dab emojis over here, so just pretend theres a dab emoji here: *dab*

**Comment by nvarner** [comment]
dab

**Comment by itsmerachel** [comment]
oh my god brilliant

**Pull request merged**
